### ISSUE TITLE
Should "all" endpoints include total page count?

### ISSUE THREAD

**Issue by greggroth** [delighted/delighted-ruby#12]
Judging by the API documentation, the API doesn't return a total page count.  Is this by design?  I understand I can iterate until the API response with an empty array, but I'd expect the total page count to be included somewhere in the response body.

**Comment by mkdynamic** [comment]
Thanks for the question @greggroth.

The original motivation for not including the total page count is because as your paginating, if new responses are arriving, that count may change. So our thinking was that iterating until you receive an empty set is better if you want to make sure you get all responses. By not including total page count, we were hoping this would become the default approach.

Could you elaborate on your use-case for wanting a total page count? I'm curious to understand that more to see if we could accommodate it.

In the meantime, if it is helpful, you can get a total count of responses from `Delighted::Metrics.retrieve[:response_count]`.

**Comment by greggroth** [comment]
>  The original motivation for not including the total page count is because as your paginating

Makes sense.  I'll stick with iterating until I get an empty array back from the API.  Thanks!
