### ISSUE TITLE
Better 404's

### ISSUE THREAD

**Issue by greggroth** [delighted/delighted-ruby#13]
This is an issue for the API as a whole, so feel free to close if there's a better place to log this complaint.  The 404 for the API is HTML, which results in a huge mess in the logs.  It would more sensible to return a response in the requested format, e.g. JSON.

Once place I've ran into this is looking up survey responses  by customer email.  The API returns a 404 if that email isn't known.  I think a more appropriate response would be an empty response with a 200 status.  A 404 should represent the state of the endpoint, so saying "yes the endpoint is here, but I'm returning a 404 because that email is missing" feels like a misuse of the status.  Analogously, it would be weird of google started returning a 404 if your search query had 0 results.

**Comment by mkdynamic** [comment]
Thanks @greggroth.

The 404 (and all error responses) should absolutely respect the Accepts header – we will definitely update the API with this change. Apologies for the pain the current HTML responses are causing.

Totally see your point on the 404 being confusing when supplying an email to the survey responses endpoint. What would you think if it returned a 404 (or perhaps a 400) but with a error message in the JSON body explaining the specific issue (i.e. no person exists with that email?). There is a case where a person exists with that email but has not submitted any responses, so thinking how to best distinguish this... Any thoughts on that would be great.

Thanks again for the feedback, very much appreciated.

**Comment by greggroth** [comment]
I would expect a 200 with an empty response body for both.  When I make this request:

```
curl https://api.delighted.com/v1/survey_responses.json \
  -u <api token>: \
  -d 'person_email=foo@bar.com'
```

I'm searching for survey responses for that person's email.  I wouldn't use that endpoint to check whether I've requested a survey from a person.  Instead, I would make a request to `v1/people`:

```
curl https://api.delighted.com/v1/people.json \
  -u <api token>: \
  -d 'email=foo@bar.com'
```


    | `v1/people.json` | `v1/survey_responses.json` |
---|-----------------------|---------------------------------------|
User doesn't exist | `[]` | `[]` |
User hasn't responded | `<user attrs>` | `[]` |
User has responded | `<user attrs>` | `<survey response attrs>` |

**Comment by mkdynamic** [comment]
@greggroth Gotcha. That makes sense. Since this is potentially a breaking change (if folks have built around the current 404 behavior) it might be a while before we introduce this, since we need to rollout versioning support to the API beforehand (which is on our roadmap). Will close this ticket for now and add more info at that point. Thanks again for the feedback, very helpful.

**Comment by jeremyboles** [comment]
A quick update on this:

We haven't changed the behavior but we did push out an update yesterday so error responses for 404 (and other errors) now return JSON instead of HTML. We also return the status code and a human-friendly message in the JSON, which might be helpful. We've updated the docs to reflect the change if you're interested in seeing an example response: https://delighted.com/docs/api

**Comment by greggroth** [comment]
That's great news!  Thank you for the update.
